data:extend({
    {
      type = "recipe-category",
      name = "auto-fabricator"
    },
    {
      type = "recipe",
      name = "iron-delivery",
      enabled = false,
      ingredients = {},
      result = "iron-plate",
      result_count = 100,
      energy_required = 1,
      category = "auto-fabricator",
      subgroup = "buildings",
    },
    {
        type = "recipe",
        name = "copper-delivery",
        enabled = false,
        ingredients = {},
        result = "copper-plate",
        result_count = 100,
        energy_required = 1,
        category = "auto-fabricator",
        subgroup = "buildings",
      },
      {
        type = "recipe",
        name = "steel-delivery",
        enabled = false,
        ingredients = {},
        result = "steel-plate",
        result_count = 100,
        energy_required = 1,
        category = "auto-fabricator",
        subgroup = "buildings",
      },
      {
        type = "recipe",
        name = "stone-delivery",
        enabled = false,
        ingredients = {},
        result = "stone-brick",
        result_count = 100,
        energy_required = 1,
        category = "auto-fabricator",
        subgroup = "buildings",
      },
      {
        type = "recipe",
        name = "uranium-delivery",
        enabled = false,
        ingredients = {},
        result = "uranium-ore",
        result_count = 50,
        energy_required = 1,
        category = "auto-fabricator",
        subgroup = "buildings",
      },
      {
        type = "recipe",
        name = "ground-auto-fabricator",
        enabled = false,
        energy_required = 1000,
        ingredients =
        {
          {"ground-fabricator-component", 4},
        },
        result = "ground-auto-fabricator",
        icon = "__expanded-rocket-payloads__/graphic/auto-fabricator-32.png",
        icon_size = 32,
        subgroup = "buildings",
        category = "satellite-crafting",
        order = "a"
      },
      {
        type = "recipe",
        name = "orbital-fabricator-component",
        energy_required = 1500,
        enabled = "false",
        ingredients = 
        {
            {"autonomous-space-mining-drone", 10},
            {"satellite-bus", 200},
            {"satellite-communications", 500},
            {"advanced-assembler", 100},
            {"electric-furnace", 500},
            {"chemical-plant", 100},            
            {"oil-refinery", 50},
            {"centrifuge", 250},
            {"stack-filter-inserter", 500},
            {"satellite-flight-computer", 250},
          },
        result = "orbital-fabricator-component",
        category = "satellite-crafting",
        subgroup = "buildings",
    },
    {
        type = "recipe",
        name = "fabricator-shuttle",
        category = "satellite-crafting",
        energy_required = 800,
        enabled = "false",
        ingredients = 
        {
          {"satellite-thruster", 50},
          {"orbital-fabricator-component", 1},
          {"shuttle-hull", 1},
        },
        result = "fabricator-shuttle",
        order = "c",
    },
    {
        type = "recipe",
        name = "refurbish-fabricator-shuttle",
        energy_required = 800,
        enabled = false,
        ingredients =
        {
          {type="item", name="water-barrel", amount=400},
          {type="item", name="stone-brick", amount=5000},
          {tpye="item", name="landed-fabricator-shuttle", amount=1},
          {tpye="item", name="rocket-fuel", amount=2000},
          {tpye="item", name="orbital-fabricator-component", amount=1},

        },
        results=
        {
          {type="item", name="fabricator-shuttle", amount=1},
          {type="item", name="ground-fabricator-component", amount=1},
          {type="item", name="empty-barrel", amount=400},
        },
        icon = "__expanded-rocket-payloads__/graphic/landed-fabricator-shuttle-32.png",
        icon_size = 32,
        subgroup = "shuttle",
        order = "f",
        category = "satellite-crafting",
    },
})